### ISSUE TITLE
failed running get_pangenomes_from_kegg.py

### ISSUE THREAD

**Issue by GuoHao150** [eltanin4/pangenome_dep#1]
Failed running the script of get_pangenomes_from_kegg.py and it gives this FileNotFoundError: [Errno 2] No such file or directory: 'strain_ecfiles/eco.txt'. Can you help me out? Thanks

**Comment by eltanin4** [comment]
Can you tell me the line number, and whether you've executed the lines that retrieve all strain enzyme class (EC) files before requesting them (there should be 931 files, I think)? 

Looking at your error, it seems the file for eco (that's E. coli in KEGG) hasn't been downloaded successfully. Try running the script again, from scratch. In my experience, urllib times out on the KEGG servers, and fails to download certain files.

**Comment by GuoHao150** [comment]
Just read your paper it's inspiring and I'm trying to reproduce the results so I can learn your approach. I did not retrieve those enzyme class. and I wonder if there is any documentation so I can better understand your scripts, I actually don't where to start with

**Comment by GuoHao150** [comment]
By the way, the error line is 66 in that script

**Comment by eltanin4** [comment]
Sorry about that. The documentation on this code is horrible, and I really haven't found the time to clean it up and properly frame it, so I can't really point you a nice document.

I will try and help you reproduce the results, though. get_pangenomes_from_kegg.py is the correct first file to run --- it pulls all the reaction data from KEGG.

Can you check for me whether you have a folder generated in your directory now called "strain_ecfiles"? And how many files are in it?

**Comment by GuoHao150** [comment]
Tried to run get_pangenomes_from_kegg.py again but it failed at the same error. It shows me this line of code `urllib.request.urlretrieve( holder + strain + '/ec', path + strain + '.txt' )` did not work out. And after this error the programme break down and the folder of "strain_ecfiles" is not generated

**Comment by eltanin4** [comment]
Create a directory called "strain_ecfiles" in your current directory. Then try again.

**Comment by GuoHao150** [comment]
Yeah, it worked and when I successfully running the script 1333 files generated in the folder of  strain_ecfiles and the `fuller_pangenome_df.csv` generated is slightly different from the one you provided looks like some species are missing. Anyway, thanks to your help and your paper, I'll keep diving your code

**Comment by eltanin4** [comment]
That's okay. KEGG keeps changing, so that may have something to do with it.
